<?php

return [
    'Ash',
    'Ashford Barbarians',
    'Ashford',
    'Askeans',
    'Aylesford Bulls',
    'Beccehamian',
    'Beckenham',
    'Bexley',
    'Blackheath',
    'Brockleians',
    'Bromley',
    'Canterbury',
    'Charlton Park',
    'Cliffe Crusaders',
    'Cranbrook',
    'Dartfordians',
    'Dartford Valley',
    'Deal Betteshanger & Walmer',
    'Dover',
    'East Peckham and Paddock Wood',
    'Edenbridge',
    'Erith',
    'Faversham',
    'Folkestone',
    'Footscray',
    'Gillingham Anchorians',
    'Gravesend',
    'Greenwich',
    'Hastings & Bexhill',
    'HSBC',
    'Kings College Hospital',
    'Leigh',
    'Lordswood',
    'Maidstone',
    'Medway',
    'New Ash Green',
    'Old Alleynian',
    'Old Colfeians',
    'Old Dunstonian',
    'Old Elthamians',
    'Old Gravesendians',
    'Old Williamsonians',
    'Orpington',
    'Park House',
    'RBS/Langley',
    'Rye',
    'Sevenoaks',
    'Sheppey',
    'Sidcup',
    'Sittingbourne',
    'Snowdown Colliery',
    'Southwark',
    'Swanley',
    'Thanet Wanderers',
    'Tonbridge Judds',
    'Tunbridge Wells',
    'Vigo',
    'Weavering Warriors',
    'Westcombe Park',
    'Whitstable'
];
